/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PreprocessConfig {
  windowSize?: number
  k?: number
  targetWidth?: number
}
export declare function preprocessImage(inputBuf: Buffer, config?: PreprocessConfig | undefined | null): Promise<Buffer>
